### ISSUE TITLE
NoCheatPlus deadlocking server due to player movement/teleport (incompatibility with Citizens)

### ISSUE THREAD

**Issue by mibby** [FearGames/NoCheatPlus#1]
NoCheatPlus dev 17 https://ci.codemc.org/job/FearGames/job/NoCheatPlus-1.14
cncp dev 91 https://ci.md-5.net/job/CompatNoCheatPlus/
Citizens2 dev 1730 https://ci.citizensnpcs.co/job/Citizens2/
Multiverse-Core dev  https://ci.onarandombox.com/job/Multiverse-Core/
ProtocolLib-Gradle dev 9 http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/
Paper dev 132 (Spigot 1.14.3) https://papermc.io/ci/view/all/job/Paper-1.14/

NoCheatPlus config v5.0.3 by @MarkElf

So I'm not exactly sure where the other ticket went, but NoCheatPlus is still causing server deadlocking presumably by Citizens according to the stacktrace dump that rarely occurs if not outright frozen. Removing NoCheatPlus, the server starts up fine, doesn't lock up, and players are able to connect without issues.

Original issue was located here, but is now gone. https://github.com/FearGames/NoCheatPlus/issues/2#issuecomment-508246784

Partially discussed here before moving to NoCheatPlus, cause found and stated by @Brokkonaut.
https://github.com/LogBlock/LogBlock/issues/760#issuecomment-507849148

Fortunately a backup of the stacktrace is located there as well.

**Comment by mibby** [comment]
Mirroring stacktrace dump and cc @mcmonkey4eva for possible insight with Citizens.

```
[14:11:33] [Paper Watchdog Thread/ERROR]: ------------------------------
[14:11:33] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[14:11:33] [Paper Watchdog Thread/ERROR]: ------------------------------
[14:11:33] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[14:11:33] [Paper Watchdog Thread/ERROR]: 	PID: 24 | Suspended: false | Native: false | State: TIMED_WAITING
[14:11:33] [Paper Watchdog Thread/ERROR]: 	Stack:
[14:11:33] [Paper Watchdog Thread/ERROR]: 		sun.misc.Unsafe.park(Native Method)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:116)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:176)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_14_R1.CraftWorld.loadChunk(CraftWorld.java:529)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_14_R1.CraftWorld.loadChunk(CraftWorld.java:416)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		fr.neatmonster.nocheatplus.utilities.map.MapUtil.ensureChunksLoaded(MapUtil.java:91)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		fr.neatmonster.nocheatplus.checks.moving.util.MovingUtil.ensureChunksLoaded(MovingUtil.java:539)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		fr.neatmonster.nocheatplus.checks.moving.MovingListener.onPlayerTeleportMonitor(MovingListener.java:1912)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		java.lang.reflect.Method.invoke(Method.java:498)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		fr.neatmonster.nocheatplus.event.mini.MultiListenerRegistry$AutoListener.onEvent(MultiListenerRegistry.java:82)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		fr.neatmonster.nocheatplus.event.mini.MiniListenerNode.onEvent(MiniListenerNode.java:157)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		fr.neatmonster.nocheatplus.event.mini.EventRegistryBukkit$4.execute(EventRegistryBukkit.java:124)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.teleport(CraftPlayer.java:765)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_14_R1.entity.CraftEntity.teleport(CraftEntity.java:489)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:258)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.citizensnpcs.EventListen.spawn(EventListen.java:637)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:607)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.citizensnpcs.EventListen.onChunkLoad(EventListen.java:145)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor401.execute(Unknown Source)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.EventExecutor$$Lambda$2893/181091715.execute(Unknown Source)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.Chunk.loadCallback(Chunk.java:628)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.PlayerChunk.lambda$null$7(PlayerChunk.java:379)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.PlayerChunk$$Lambda$3360/659281615.accept(Unknown Source)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.PlayerChunk.lambda$a$8(PlayerChunk.java:377)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.PlayerChunk$$Lambda$3276/1443644870.accept(Unknown Source)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:580)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.ChunkTaskQueueSorter.b(SourceFile:57)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.ChunkTaskQueueSorter$$Lambda$3297/258459170.run(Unknown Source)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.ThreadedMailbox.e(SourceFile:83)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.ThreadedMailbox.a(SourceFile:123)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.ThreadedMailbox.run(SourceFile:91)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:597)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:176)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:369)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.IWorldReader.getChunkAt(IWorldReader.java:80)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:330)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.World.getType(World.java:721)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.getNMS(CraftBlock.java:69)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.isEmpty(CraftBlock.java:590)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		com.benzoft.gravitytubes.GravityTube.hasSourceBlock(GravityTube.java:50)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		com.benzoft.gravitytubes.GravityTubes.lambda$null$1(GravityTubes.java:35)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		com.benzoft.gravitytubes.GravityTubes$$Lambda$4390/509105851.test(Unknown Source)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		com.benzoft.gravitytubes.GravityTubes.lambda$onEnable$3(GravityTubes.java:35)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		com.benzoft.gravitytubes.GravityTubes$$Lambda$3439/1981416304.run(Unknown Source)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1132)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
[14:11:33] [Paper Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:748)
```

**Comment by mcmonkey4eva** [comment]
@mibby that stack trace was not generated on build 1730 and further _cannot_ be generated on build 1730, as it is a stracktrace of an issue that was resolved several builds ago.

**Comment by mibby** [comment]
@mcmonkey4eva I'm just reposting the old stacktrace from the former issue that is now gone. As the stacktrace does not generate every time the server deadlocks, I don't wish to continuously restart for hours until one finally does appear again. 

I've still managed to reproduce the deadlocking issue consistently with the versions reported above however. Removing either NoCheatPlus or Citizens, the start-up deadlocking goes away.

**Comment by mcmonkey4eva** [comment]
Perhaps open an old log file from where it deadlocked on a current build of Citizens? (The server stores all the old files, it just zips them)

**Comment by mibby** [comment]
Old log files don't have a stacktrace from a newer version since the dump was from the versions released and tested at that time. However it was only a handful of builds behind what's out now (dev 1717) and nothing significant seems to have changed since. 

This new issue ticket created has updated dev versions reported above because I re-tested and still experience the deadlocking with the latest releases involved. I'll try to get a new stacktrace dump but I doubt anything significant has changed and don't want to be sitting restarting the server for hours until a stacktrace actually produces itself since it doesn't occur when the main thread is deadlocked and frozen. :(

**Comment by mibby** [comment]
Re-testing with newer versions on 1.14.4, this no longer seems to be occurring! Hooray!

Paper dev 136 (Spigot 1.14.4)
Citizens dev 1733
NoCheatPlus dev 18
cncp dev 91
ProtocolLib-Gradle dev 9

I did also remove ViaVersion, ProtocolSupport, and WorldGuardExtraFlags with 1.14.4 update if any of those were causing a conflict. But seeing as I personally am no longer able to reproduce this conflict and deadlocking issue between Citizens and NoCheatPlus, I'll close the ticket. :)
